[tool.black]
line-length = 88
target-version = ['py312']
force-exclude = '''
/(
    venv
    | \.auth
    | \.git
    | \.gitignore
)/
'''


[tool.isort]
profile = "black"  # Критически важно: заставляет isort работать по правилам Black
line_length = 88
